ecommerce_pipeline:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: ecommerce-data-platform-497218
      dataset: ecommerce_pipeline
      location: US
      keyfile: "{{ env_var('DBT_KEYFILE_PATH') }}"
      threads: 4
      timeout_seconds: 300